### PR TITLE
Fixed rgd & depth synchronization. Changed depth format to 16 bit. Added command line parameter. 

### PR DESCRIPTION
**Pull request by RaresAmbrus**
Fixed rgd & depth synchronization by adding a buffer and saving images only when they have been matched. Changed the format of the depth image from 32 to 16 bit. Added a command line paramenter _saveMismatched to indicate whether to save all the images or only those with a match

### CODE REVIEW

**Comment by cdondrup** [comment]
I don't know if that might be interesting for you but you don't have to do the syncing yourself. ROS does this for you and guaranties thread safety while doing so. What it does is building a queue for your subscribers and try to match the time stamps according to different policies (e.g. exact vs. approximate) and calls just one callback with all the matched messages. Here is what we do to synchronise depth and color images in the pedestrian detection:

``` cpp
...
#include <message_filters/subscriber.h>
#include <message_filters/synchronizer.h>
#include <message_filters/sync_policies/approximate_time.h>
#include <sensor_msgs/Image.h>
...

using namespace sensor_msgs;
using namespace message_filters;
...

void callback(const ImageConstPtr &depth,  const ImageConstPtr &color)
{
// Do some magic
}
...
int main(int argc, char **argv)
{
    // Set up ROS.
    ros::init(argc, argv, "my_node");
    ros::NodeHandle n;
    ...

    // Set queue size to 1 for the subscriber
    Subscriber<Image> subscriber_depth(n, topic_depth_image.c_str(), 1);
    Subscriber<Image> subscriber_color(n, topic_color_image.c_str(), 1);

    //The real queue size for synchronisation is set here: 5.
    sync_policies::ApproximateTime<Image, Image> MySyncPolicy(5)

    // Create synchronization policy. Here: approx because time stamps will never match exactly
    const sync_policies::ApproximateTime<Image, Image> MyConstSyncPolicy = MySyncPolicy;
    Synchronizer< sync_policies::ApproximateTime<Image, Image> > sync(MyConstSyncPolicy,
                                                                                               subscriber_depth,
                                                                                               subscriber_color);
    // Register one callback for all topics
    sync.registerCallback(boost::bind(&callback, _1, _2));
    ...

   ros::spin();
}
```

So here we are creating two message_filters::Subscribers and use the approximate synchronisation policy because the kinect images will moste likely never have the exact same timestamp. Afterwards we register our callback to both subscribers. The whole `sync_policies` and `const sync_policies` stuff is kind of necessary if you want to set an age penalty or similar. If you are happy with the standard synchronisation you can directely create a const sync policy. This works with up to 9 different subscribers and in addition you can also still assign callbacks to just one of the subscribers.

I don't know if that is of any use for you but if you need any further information you can have a look at: http://www.ros.org/wiki/message_filters

**Comment by RaresAmbrus** [comment]
@cdondrup thanks for the heads up - I'll look into it and use it next time. 
Btw. have you checked that this works properly ? (sometimes images don't come in order, i.e. rgb_1, rgb_2, rgb_3, depth_1, with depth_1 being closer to rgb_2 than rgb_1 or viceversa).

**Comment by cdondrup** [comment]
I don't know if I understand your problem correctly. What do you mean by closer? If you mean close in the sense that the timestamps are closer together, then depth1 and rgb2 (in your example) would be published together because synchronisation only works according to timestamps. But maybe I misunderstood your concern. The algorithm used for the approximate sync is explained here: http://www.ros.org/wiki/message_filters/ApproximateTime maybe that helps clarify things.

**Comment by RaresAmbrus** [comment]
@cdondrup got it now - some messages are dropped if there are better matches; thanks again!

**Comment by cdondrup** [comment]
@RaresAmbrus No problem. It took us a few hours to find the right solution to this problem. So I just wanted to give you a heads up. Hope it's useful in the future.

**Pull request merged**
